spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 327697859230-227mkdtpas8c0k8fs4dagq1efb0s7kdo.apps.googleusercontent.com
            client-secret: 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
          apple:
            client-id:
            client-secret: