spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kids_app_test
    username: root
    password: 12344321

  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enable-spring-el-compiler: true
    mode: HTML
  mail:
    host: smtp.yandex.ru
    port: 465
    username: KidsAppTestAcc@yandex.by
    password: fzdvpfqdpoxolwvp
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

#firebase:
#  config:
#    type: ${FIREBASE_CONFIG_TYPE}
#    project_id: ${FIREBASE_PROJECT_ID}
#    private_key_id: ${FIREBASE_PRIVATE_KEY_ID}
#    private_key: ${FIREBASE_PRIVATE_KEY}
#    client_email: ${FIREBASE_CLIENT_EMAIL}
#    client_id: ${FIREBASE_CLIENT_ID}
#    auth_uri: ${FIREBASE_CLIENT_URI}
#    token_uri: ${FIREBASE_TOKEN_URI}
#    auth_provider_x509_cert_url: ${FIREBASE_PROVIDER_X509_CERT_IRL}
#    client_x509_cert_url: ${FIREBASE_CLIENT_X509_CERT_URL}




security:
  firebase-props:
    database-url: ${spring.datasource.url}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
  exposed-headers:
    - X-Xsrf-Token